# routes.yml

prettyblocks_admin_index:
  path: /prettyblocks/admin
  methods: [ GET ]
  defaults:
    _controller: PrestaSafe\PrettyBlocks\Controller\Admin\EditionController::indexAction
    _legacy_controller: PrettyBlocksAdminEdition
    _legacy_link: PrettyBlocksAdminEdition

prettyblocks_admin_edit:
  path: /prettyblocks/admin/edit
  methods: [ GET ]
  defaults:
      _controller: PrestaSafe\PrettyBlocks\Controller\Admin\EditionController::editAction
      _legacy_controller: PrettyBlocksAdminEdition
      _legacy_link: PrettyBlocksAdminEdition

prettyblocks_zone_list:
  path: /prettyblocks/api/zones
  methods: [ GET ]
  defaults:
    _controller: PrestaSafe\PrettyBlocks\Controller\Api\ZoneController:listZones
    _legacy_controller: PrettyBlocksApiZone
    _legacy_link: PrettyBlocksApiZone

prettyblocks_zone_get:
  path: /prettyblocks/api/zones/{id}
  methods: [ GET ]
  defaults:
    _controller: PrestaSafe\PrettyBlocks\Controller\Api\ZoneController:getZone
    _legacy_controller: PrettyBlocksApiZone
    _legacy_link: PrettyBlocksApiZone

prettyblocks_zone_fields:
  path: /prettyblocks/api/zones/{id}/fields
  methods: [ GET ]
  defaults:
    _controller: PrestaSafe\PrettyBlocks\Controller\Api\ZoneController:getZoneFields
    _legacy_controller: PrettyBlocksApiZone
    _legacy_link: PrettyBlocksApiZone

prettyblocks_zone_update:
  path: /prettyblocks/api/zones/{id}
  methods: [ PUT ]
  defaults:
    _controller: PrestaSafe\PrettyBlocks\Controller\Api\ZoneController:updateZone
    _legacy_controller: PrettyBlocksApiZone
    _legacy_link: PrettyBlocksApiZone

prettyblocks_media_upload:
  path: /prettyblocks/api/media/upload
  methods: [ POST ]
  defaults:
    _controller: PrestaSafe\PrettyBlocks\Controller\Api\MediaController:uploadMedia
    _legacy_controller: PrettyBlocksApiMedia
    _legacy_link: PrettyBlocksApiMedia

prettyblocks_field_list:
  path: /prettyblocks/api/fields
  methods: [ GET ]
  defaults:
    _controller: PrestaSafe\PrettyBlocks\Controller\Api\FieldController:listAction
    _legacy_controller: PrettyBlocksApiField
    _legacy_link: PrettyBlocksApiField


