<?php

declare(strict_types=1);

namespace PrestaSafe\PrettyBlocks\FieldType\Primitive;

class MapPrimitiveFieldType extends AbstractPrimitiveFieldType
{
    public function getType(): string
    {
        return 'map';
    }

    public function getDefaultValue(): array
    {
        return [];
    }

    public function getDefault(): array
    {
        return parent::getDefault(); // TODO: Change the autogenerated stub
    }
}
